# OpenAI / ChatGPT
DOMAIN-SUFFIX,openai.com
DOMAIN-SUFFIX,oaistatic.com
DOMAIN-SUFFIX,sora.com
DOMAIN-SUFFIX,chatgpt.com
DOMAIN-SUFFIX,chat.com
DOMAIN-SUFFIX,ai.com
DOMAIN-KEYWORD,openai

# Perplexity
DOMAIN-SUFFIX,perplexity.ai

# Claude
DOMAIN-SUFFIX,anthropic.com
DOMAIN-SUFFIX,claude.ai
DOMAIN-SUFFIX,claude.com

# Google Gemini / Bard / DeepMind / Generative AI
DOMAIN-SUFFIX,bard.google.com
DOMAIN-SUFFIX,gemini.google
DOMAIN-SUFFIX,gemini.google.com
DOMAIN,aisandbox-pa.googleapis.com
DOMAIN,robinfrontend-pa.googleapis.com
DOMAIN-SUFFIX,deepmind.com
DOMAIN-SUFFIX,deepmind.google
DOMAIN-SUFFIX,generativelanguage.googleapis.com
DOMAIN-SUFFIX,geller-pa.googleapis.com
DOMAIN-SUFFIX,proactivebackend-pa.googleapis.com
DOMAIN-SUFFIX,cloudcode-pa.googleapis.com
DOMAIN,ai.google.dev
DOMAIN-SUFFIX,aistudio.google.com
DOMAIN-SUFFIX,makersuite.google.com
DOMAIN,alkalicore-pa.clients6.google.com
DOMAIN-KEYWORD,alkalimakersuite-pa.clients6.google.com
DOMAIN-SUFFIX,generativeai.google
DOMAIN-SUFFIX,notebooklm.google
DOMAIN-SUFFIX,notebooklm.google.com
DOMAIN,jules.google.com
DOMAIN,aida.googleapis.com
DOMAIN,antigravity.google

# POE
DOMAIN-SUFFIX,poe.com

# Meta AI
DOMAIN-SUFFIX,meta.ai

# Cloudflare AI Gateway
DOMAIN,gateway.ai.cloudflare.com

# Dify.AI
DOMAIN-SUFFIX,dify.ai

# Jasper
DOMAIN-SUFFIX,clipdrop.co
DOMAIN-SUFFIX,jasper.ai

# OpenArt
DOMAIN-SUFFIX,openart.ai

# GitHub Copilot
DOMAIN,api.github.com

# Grok
DOMAIN-SUFFIX,grok.com
DOMAIN-SUFFIX,x.ai

# groq
DOMAIN-SUFFIX,groq.com

# JetBrains AI
DOMAIN,api.jetbrains.ai

# OpenRouter AI
DOMAIN,openrouter.ai

# Cursor AI
DOMAIN-SUFFIX,cursor.sh
DOMAIN-SUFFIX,cursor.com
DOMAIN-SUFFIX,cursor-cdn.com
DOMAIN-SUFFIX,cursorapi.com

# Nvidia
DOMAIN-SUFFIX,nvidia.com
